name: Django application deployment

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/django-api:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/django-api:${{ github.sha }}
