name: Django application deployment

on: [workflow_dispatch]

jobs:

  # Build docker image and push on AZ container registry
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/django-api:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/django-api:${{ github.sha }}

  # Deploy a new app service from the docker image
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: django-rappers
        images: ${{ secrets.REGISTRY_NAME }}.azurecr.io/django-api:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        app-settings-json: ${{ secrets.APP_SETTINGS }}